# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginServiceStub:
    """============================================
    Core service — every plugin MUST implement
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/hugo_admin.plugin.PluginService/Info',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.PluginInfo.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hugo_admin.plugin.PluginService/HealthCheck',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetConfigSchema = channel.unary_unary(
                '/hugo_admin.plugin.PluginService/GetConfigSchema',
                request_serializer=plugin__pb2.Empty.SerializeToString,
                response_deserializer=plugin__pb2.ConfigSchemaResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/hugo_admin.plugin.PluginService/SetConfig',
                request_serializer=plugin__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=plugin__pb2.SetConfigResponse.FromString,
                _registered_method=True)


class PluginServiceServicer:
    """============================================
    Core service — every plugin MUST implement
    ============================================

    """

    def Info(self, request, context):
        """Return plugin metadata and supported capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Liveness probe; Plugin Manager calls this during handshake
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfigSchema(self, request, context):
        """Return the JSON Schema for user-configurable settings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Push user configuration (decrypted by host before sending)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.PluginInfo.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.HealthResponse.SerializeToString,
            ),
            'GetConfigSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfigSchema,
                    request_deserializer=plugin__pb2.Empty.FromString,
                    response_serializer=plugin__pb2.ConfigSchemaResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=plugin__pb2.SetConfigRequest.FromString,
                    response_serializer=plugin__pb2.SetConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hugo_admin.plugin.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hugo_admin.plugin.PluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginService:
    """============================================
    Core service — every plugin MUST implement
    ============================================

    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hugo_admin.plugin.PluginService/Info',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.PluginInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hugo_admin.plugin.PluginService/HealthCheck',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfigSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hugo_admin.plugin.PluginService/GetConfigSchema',
            plugin__pb2.Empty.SerializeToString,
            plugin__pb2.ConfigSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hugo_admin.plugin.PluginService/SetConfig',
            plugin__pb2.SetConfigRequest.SerializeToString,
            plugin__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImageUploaderStub:
    """============================================
    Optional capability: Image Upload
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/hugo_admin.plugin.ImageUploader/Upload',
                request_serializer=plugin__pb2.ImageUploadChunk.SerializeToString,
                response_deserializer=plugin__pb2.ImageUploadResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/hugo_admin.plugin.ImageUploader/Delete',
                request_serializer=plugin__pb2.ImageDeleteRequest.SerializeToString,
                response_deserializer=plugin__pb2.ImageDeleteResponse.FromString,
                _registered_method=True)


class ImageUploaderServicer:
    """============================================
    Optional capability: Image Upload
    ============================================

    """

    def Upload(self, request_iterator, context):
        """Client-streaming: host sends file in 64 KiB chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageUploaderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=plugin__pb2.ImageUploadChunk.FromString,
                    response_serializer=plugin__pb2.ImageUploadResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=plugin__pb2.ImageDeleteRequest.FromString,
                    response_serializer=plugin__pb2.ImageDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hugo_admin.plugin.ImageUploader', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hugo_admin.plugin.ImageUploader', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageUploader:
    """============================================
    Optional capability: Image Upload
    ============================================

    """

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/hugo_admin.plugin.ImageUploader/Upload',
            plugin__pb2.ImageUploadChunk.SerializeToString,
            plugin__pb2.ImageUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hugo_admin.plugin.ImageUploader/Delete',
            plugin__pb2.ImageDeleteRequest.SerializeToString,
            plugin__pb2.ImageDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TTSGeneratorStub:
    """============================================
    Optional capability: TTS (text-to-speech)
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/hugo_admin.plugin.TTSGenerator/Generate',
                request_serializer=plugin__pb2.TTSRequest.SerializeToString,
                response_deserializer=plugin__pb2.TTSResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/hugo_admin.plugin.TTSGenerator/Delete',
                request_serializer=plugin__pb2.TTSDeleteRequest.SerializeToString,
                response_deserializer=plugin__pb2.TTSDeleteResponse.FromString,
                _registered_method=True)


class TTSGeneratorServicer:
    """============================================
    Optional capability: TTS (text-to-speech)
    ============================================

    """

    def Generate(self, request, context):
        """Server-streaming: plugin emits Progress messages while synthesizing,
        and a final Result carrying the public audio URL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete a previously generated/hosted audio object.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=plugin__pb2.TTSRequest.FromString,
                    response_serializer=plugin__pb2.TTSResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=plugin__pb2.TTSDeleteRequest.FromString,
                    response_serializer=plugin__pb2.TTSDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hugo_admin.plugin.TTSGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hugo_admin.plugin.TTSGenerator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSGenerator:
    """============================================
    Optional capability: TTS (text-to-speech)
    ============================================

    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hugo_admin.plugin.TTSGenerator/Generate',
            plugin__pb2.TTSRequest.SerializeToString,
            plugin__pb2.TTSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hugo_admin.plugin.TTSGenerator/Delete',
            plugin__pb2.TTSDeleteRequest.SerializeToString,
            plugin__pb2.TTSDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
