// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author          string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // must match host's expected version
	Capabilities    []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                              // e.g. "image_upload"
	Priority        int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`                                     // higher = preferred when multiple plugins share a capability
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *PluginInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // optional detail when unhealthy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaJson    string                 `protobuf:"bytes,1,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"` // JSON Schema string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchemaResponse) Reset() {
	*x = ConfigSchemaResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchemaResponse) ProtoMessage() {}

func (x *ConfigSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchemaResponse.ProtoReflect.Descriptor instead.
func (*ConfigSchemaResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigSchemaResponse) GetSchemaJson() string {
	if x != nil {
		return x.SchemaJson
	}
	return ""
}

type SetConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON object with decrypted config values
	ConfigJson    string `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *SetConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *SetConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImageUploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                  // file content chunk (up to 64 KiB)
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                          // original filename (sent on first chunk)
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`          // e.g. "image/png" (sent on first chunk)
	ArticlePath   string                 `protobuf:"bytes,4,opt,name=article_path,json=articlePath,proto3" json:"article_path,omitempty"` // target article path for context (sent on first chunk)
	IsLast        bool                   `protobuf:"varint,5,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`               // true on the final chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUploadChunk) Reset() {
	*x = ImageUploadChunk{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUploadChunk) ProtoMessage() {}

func (x *ImageUploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUploadChunk.ProtoReflect.Descriptor instead.
func (*ImageUploadChunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ImageUploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageUploadChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageUploadChunk) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageUploadChunk) GetArticlePath() string {
	if x != nil {
		return x.ArticlePath
	}
	return ""
}

func (x *ImageUploadChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type ImageUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                        // public CDN URL of the uploaded image
	ImageId       string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"` // provider-specific ID for later deletion
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                // error detail when success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUploadResponse) Reset() {
	*x = ImageUploadResponse{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUploadResponse) ProtoMessage() {}

func (x *ImageUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUploadResponse.ProtoReflect.Descriptor instead.
func (*ImageUploadResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ImageUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImageUploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageUploadResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDeleteRequest) Reset() {
	*x = ImageDeleteRequest{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDeleteRequest) ProtoMessage() {}

func (x *ImageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDeleteRequest.ProtoReflect.Descriptor instead.
func (*ImageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ImageDeleteRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type ImageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDeleteResponse) Reset() {
	*x = ImageDeleteResponse{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDeleteResponse) ProtoMessage() {}

func (x *ImageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDeleteResponse.ProtoReflect.Descriptor instead.
func (*ImageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ImageDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImageDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                  // text to synthesize (article body, no frontmatter)
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`                                // voice id, e.g. "mimo_default"
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                // e.g. "mimo-v2.5-tts"
	Speed         float32                `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`                              // 0.5–2.0, 1.0 = normal
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`                              // "mp3" (default) | "wav"
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`                          // optional BCP-47 hint
	ArticlePath   string                 `protobuf:"bytes,7,opt,name=article_path,json=articlePath,proto3" json:"article_path,omitempty"` // article path for context (e.g. object key naming)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSRequest) Reset() {
	*x = TTSRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSRequest) ProtoMessage() {}

func (x *TTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSRequest.ProtoReflect.Descriptor instead.
func (*TTSRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *TTSRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TTSRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *TTSRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TTSRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *TTSRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TTSRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TTSRequest) GetArticlePath() string {
	if x != nil {
		return x.ArticlePath
	}
	return ""
}

// A single streamed response: either a progress update or the final result.
type TTSResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TTSResponse_Progress
	//	*TTSResponse_Result
	Payload       isTTSResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSResponse) Reset() {
	*x = TTSResponse{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSResponse) ProtoMessage() {}

func (x *TTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSResponse.ProtoReflect.Descriptor instead.
func (*TTSResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *TTSResponse) GetPayload() isTTSResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TTSResponse) GetProgress() *TTSProgress {
	if x != nil {
		if x, ok := x.Payload.(*TTSResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *TTSResponse) GetResult() *TTSResult {
	if x != nil {
		if x, ok := x.Payload.(*TTSResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isTTSResponse_Payload interface {
	isTTSResponse_Payload()
}

type TTSResponse_Progress struct {
	Progress *TTSProgress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type TTSResponse_Result struct {
	Result *TTSResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*TTSResponse_Progress) isTTSResponse_Payload() {}

func (*TTSResponse_Result) isTTSResponse_Payload() {}

type TTSProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`       // e.g. "synthesizing" | "uploading"
	Percent       float32                `protobuf:"fixed32,2,opt,name=percent,proto3" json:"percent,omitempty"` // 0.0–100.0
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`   // optional human-readable detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSProgress) Reset() {
	*x = TTSProgress{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSProgress) ProtoMessage() {}

func (x *TTSProgress) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSProgress.ProtoReflect.Descriptor instead.
func (*TTSProgress) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *TTSProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *TTSProgress) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *TTSProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TTSResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                                                  // public audio URL (e.g. Cloudflare R2)
	DurationSeconds float32                `protobuf:"fixed32,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // audio length, 0 if unknown
	AudioId         string                 `protobuf:"bytes,4,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`                           // provider-specific id for later Delete
	Format          string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`                                            // actual delivered format, e.g. "mp3"
	Message         string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                          // error detail when success=false
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TTSResult) Reset() {
	*x = TTSResult{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSResult) ProtoMessage() {}

func (x *TTSResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSResult.ProtoReflect.Descriptor instead.
func (*TTSResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *TTSResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TTSResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TTSResult) GetDurationSeconds() float32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TTSResult) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *TTSResult) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TTSResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TTSDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSDeleteRequest) Reset() {
	*x = TTSDeleteRequest{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSDeleteRequest) ProtoMessage() {}

func (x *TTSDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSDeleteRequest.ProtoReflect.Descriptor instead.
func (*TTSDeleteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *TTSDeleteRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

type TTSDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSDeleteResponse) Reset() {
	*x = TTSDeleteResponse{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSDeleteResponse) ProtoMessage() {}

func (x *TTSDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSDeleteResponse.ProtoReflect.Descriptor instead.
func (*TTSDeleteResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *TTSDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TTSDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x11hugo_admin.plugin\"\a\n" +
	"\x05Empty\"\xdf\x01\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\tR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x14ConfigSchemaResponse\x12\x1f\n" +
	"\vschema_json\x18\x01 \x01(\tR\n" +
	"schemaJson\"3\n" +
	"\x10SetConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"G\n" +
	"\x11SetConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x10ImageUploadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12!\n" +
	"\farticle_path\x18\x04 \x01(\tR\varticlePath\x12\x17\n" +
	"\ais_last\x18\x05 \x01(\bR\x06isLast\"v\n" +
	"\x13ImageUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"/\n" +
	"\x12ImageDeleteRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\"I\n" +
	"\x13ImageDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x01\n" +
	"\n" +
	"TTSRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x02R\x05speed\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12!\n" +
	"\farticle_path\x18\a \x01(\tR\varticlePath\"\x8e\x01\n" +
	"\vTTSResponse\x12<\n" +
	"\bprogress\x18\x01 \x01(\v2\x1e.hugo_admin.plugin.TTSProgressH\x00R\bprogress\x126\n" +
	"\x06result\x18\x02 \x01(\v2\x1c.hugo_admin.plugin.TTSResultH\x00R\x06resultB\t\n" +
	"\apayload\"W\n" +
	"\vTTSProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x02R\apercent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xaf\x01\n" +
	"\tTTSResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x02R\x0fdurationSeconds\x12\x19\n" +
	"\baudio_id\x18\x04 \x01(\tR\aaudioId\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"-\n" +
	"\x10TTSDeleteRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\"G\n" +
	"\x11TTSDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xca\x02\n" +
	"\rPluginService\x12?\n" +
	"\x04Info\x12\x18.hugo_admin.plugin.Empty\x1a\x1d.hugo_admin.plugin.PluginInfo\x12J\n" +
	"\vHealthCheck\x12\x18.hugo_admin.plugin.Empty\x1a!.hugo_admin.plugin.HealthResponse\x12T\n" +
	"\x0fGetConfigSchema\x12\x18.hugo_admin.plugin.Empty\x1a'.hugo_admin.plugin.ConfigSchemaResponse\x12V\n" +
	"\tSetConfig\x12#.hugo_admin.plugin.SetConfigRequest\x1a$.hugo_admin.plugin.SetConfigResponse2\xc1\x01\n" +
	"\rImageUploader\x12W\n" +
	"\x06Upload\x12#.hugo_admin.plugin.ImageUploadChunk\x1a&.hugo_admin.plugin.ImageUploadResponse(\x01\x12W\n" +
	"\x06Delete\x12%.hugo_admin.plugin.ImageDeleteRequest\x1a&.hugo_admin.plugin.ImageDeleteResponse2\xb0\x01\n" +
	"\fTTSGenerator\x12K\n" +
	"\bGenerate\x12\x1d.hugo_admin.plugin.TTSRequest\x1a\x1e.hugo_admin.plugin.TTSResponse0\x01\x12S\n" +
	"\x06Delete\x12#.hugo_admin.plugin.TTSDeleteRequest\x1a$.hugo_admin.plugin.TTSDeleteResponseB$Z\"github.com/svtter/hugo-admin/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),                // 0: hugo_admin.plugin.Empty
	(*PluginInfo)(nil),           // 1: hugo_admin.plugin.PluginInfo
	(*HealthResponse)(nil),       // 2: hugo_admin.plugin.HealthResponse
	(*ConfigSchemaResponse)(nil), // 3: hugo_admin.plugin.ConfigSchemaResponse
	(*SetConfigRequest)(nil),     // 4: hugo_admin.plugin.SetConfigRequest
	(*SetConfigResponse)(nil),    // 5: hugo_admin.plugin.SetConfigResponse
	(*ImageUploadChunk)(nil),     // 6: hugo_admin.plugin.ImageUploadChunk
	(*ImageUploadResponse)(nil),  // 7: hugo_admin.plugin.ImageUploadResponse
	(*ImageDeleteRequest)(nil),   // 8: hugo_admin.plugin.ImageDeleteRequest
	(*ImageDeleteResponse)(nil),  // 9: hugo_admin.plugin.ImageDeleteResponse
	(*TTSRequest)(nil),           // 10: hugo_admin.plugin.TTSRequest
	(*TTSResponse)(nil),          // 11: hugo_admin.plugin.TTSResponse
	(*TTSProgress)(nil),          // 12: hugo_admin.plugin.TTSProgress
	(*TTSResult)(nil),            // 13: hugo_admin.plugin.TTSResult
	(*TTSDeleteRequest)(nil),     // 14: hugo_admin.plugin.TTSDeleteRequest
	(*TTSDeleteResponse)(nil),    // 15: hugo_admin.plugin.TTSDeleteResponse
}
var file_plugin_proto_depIdxs = []int32{
	12, // 0: hugo_admin.plugin.TTSResponse.progress:type_name -> hugo_admin.plugin.TTSProgress
	13, // 1: hugo_admin.plugin.TTSResponse.result:type_name -> hugo_admin.plugin.TTSResult
	0,  // 2: hugo_admin.plugin.PluginService.Info:input_type -> hugo_admin.plugin.Empty
	0,  // 3: hugo_admin.plugin.PluginService.HealthCheck:input_type -> hugo_admin.plugin.Empty
	0,  // 4: hugo_admin.plugin.PluginService.GetConfigSchema:input_type -> hugo_admin.plugin.Empty
	4,  // 5: hugo_admin.plugin.PluginService.SetConfig:input_type -> hugo_admin.plugin.SetConfigRequest
	6,  // 6: hugo_admin.plugin.ImageUploader.Upload:input_type -> hugo_admin.plugin.ImageUploadChunk
	8,  // 7: hugo_admin.plugin.ImageUploader.Delete:input_type -> hugo_admin.plugin.ImageDeleteRequest
	10, // 8: hugo_admin.plugin.TTSGenerator.Generate:input_type -> hugo_admin.plugin.TTSRequest
	14, // 9: hugo_admin.plugin.TTSGenerator.Delete:input_type -> hugo_admin.plugin.TTSDeleteRequest
	1,  // 10: hugo_admin.plugin.PluginService.Info:output_type -> hugo_admin.plugin.PluginInfo
	2,  // 11: hugo_admin.plugin.PluginService.HealthCheck:output_type -> hugo_admin.plugin.HealthResponse
	3,  // 12: hugo_admin.plugin.PluginService.GetConfigSchema:output_type -> hugo_admin.plugin.ConfigSchemaResponse
	5,  // 13: hugo_admin.plugin.PluginService.SetConfig:output_type -> hugo_admin.plugin.SetConfigResponse
	7,  // 14: hugo_admin.plugin.ImageUploader.Upload:output_type -> hugo_admin.plugin.ImageUploadResponse
	9,  // 15: hugo_admin.plugin.ImageUploader.Delete:output_type -> hugo_admin.plugin.ImageDeleteResponse
	11, // 16: hugo_admin.plugin.TTSGenerator.Generate:output_type -> hugo_admin.plugin.TTSResponse
	15, // 17: hugo_admin.plugin.TTSGenerator.Delete:output_type -> hugo_admin.plugin.TTSDeleteResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[11].OneofWrappers = []any{
		(*TTSResponse_Progress)(nil),
		(*TTSResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
