// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.24.4
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Info_FullMethodName            = "/hugo_admin.plugin.PluginService/Info"
	PluginService_HealthCheck_FullMethodName     = "/hugo_admin.plugin.PluginService/HealthCheck"
	PluginService_GetConfigSchema_FullMethodName = "/hugo_admin.plugin.PluginService/GetConfigSchema"
	PluginService_SetConfig_FullMethodName       = "/hugo_admin.plugin.PluginService/SetConfig"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	// Return plugin metadata and supported capabilities
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	// Liveness probe; Plugin Manager calls this during handshake
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// Return the JSON Schema for user-configurable settings
	GetConfigSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigSchemaResponse, error)
	// Push user configuration (decrypted by host before sending)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, PluginService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetConfigSchema(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigSchemaResponse)
	err := c.cc.Invoke(ctx, PluginService_GetConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, PluginService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
type PluginServiceServer interface {
	// Return plugin metadata and supported capabilities
	Info(context.Context, *Empty) (*PluginInfo, error)
	// Liveness probe; Plugin Manager calls this during handshake
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	// Return the JSON Schema for user-configurable settings
	GetConfigSchema(context.Context, *Empty) (*ConfigSchemaResponse, error)
	// Push user configuration (decrypted by host before sending)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedPluginServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginServiceServer) GetConfigSchema(context.Context, *Empty) (*ConfigSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigSchema not implemented")
}
func (UnimplementedPluginServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetConfigSchema(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hugo_admin.plugin.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _PluginService_Info_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginService_HealthCheck_Handler,
		},
		{
			MethodName: "GetConfigSchema",
			Handler:    _PluginService_GetConfigSchema_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _PluginService_SetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	ImageUploader_Upload_FullMethodName = "/hugo_admin.plugin.ImageUploader/Upload"
	ImageUploader_Delete_FullMethodName = "/hugo_admin.plugin.ImageUploader/Delete"
)

// ImageUploaderClient is the client API for ImageUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageUploaderClient interface {
	// Client-streaming: host sends file in 64 KiB chunks
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImageUploadChunk, ImageUploadResponse], error)
	Delete(ctx context.Context, in *ImageDeleteRequest, opts ...grpc.CallOption) (*ImageDeleteResponse, error)
}

type imageUploaderClient struct {
	cc grpc.ClientConnInterface
}

func NewImageUploaderClient(cc grpc.ClientConnInterface) ImageUploaderClient {
	return &imageUploaderClient{cc}
}

func (c *imageUploaderClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImageUploadChunk, ImageUploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImageUploader_ServiceDesc.Streams[0], ImageUploader_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageUploadChunk, ImageUploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageUploader_UploadClient = grpc.ClientStreamingClient[ImageUploadChunk, ImageUploadResponse]

func (c *imageUploaderClient) Delete(ctx context.Context, in *ImageDeleteRequest, opts ...grpc.CallOption) (*ImageDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageDeleteResponse)
	err := c.cc.Invoke(ctx, ImageUploader_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageUploaderServer is the server API for ImageUploader service.
// All implementations must embed UnimplementedImageUploaderServer
// for forward compatibility.
type ImageUploaderServer interface {
	// Client-streaming: host sends file in 64 KiB chunks
	Upload(grpc.ClientStreamingServer[ImageUploadChunk, ImageUploadResponse]) error
	Delete(context.Context, *ImageDeleteRequest) (*ImageDeleteResponse, error)
	mustEmbedUnimplementedImageUploaderServer()
}

// UnimplementedImageUploaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageUploaderServer struct{}

func (UnimplementedImageUploaderServer) Upload(grpc.ClientStreamingServer[ImageUploadChunk, ImageUploadResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedImageUploaderServer) Delete(context.Context, *ImageDeleteRequest) (*ImageDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedImageUploaderServer) mustEmbedUnimplementedImageUploaderServer() {}
func (UnimplementedImageUploaderServer) testEmbeddedByValue()                       {}

// UnsafeImageUploaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageUploaderServer will
// result in compilation errors.
type UnsafeImageUploaderServer interface {
	mustEmbedUnimplementedImageUploaderServer()
}

func RegisterImageUploaderServer(s grpc.ServiceRegistrar, srv ImageUploaderServer) {
	// If the following call panics, it indicates UnimplementedImageUploaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageUploader_ServiceDesc, srv)
}

func _ImageUploader_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageUploaderServer).Upload(&grpc.GenericServerStream[ImageUploadChunk, ImageUploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageUploader_UploadServer = grpc.ClientStreamingServer[ImageUploadChunk, ImageUploadResponse]

func _ImageUploader_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageUploaderServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageUploader_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageUploaderServer).Delete(ctx, req.(*ImageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageUploader_ServiceDesc is the grpc.ServiceDesc for ImageUploader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageUploader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hugo_admin.plugin.ImageUploader",
	HandlerType: (*ImageUploaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _ImageUploader_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _ImageUploader_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	TTSGenerator_Generate_FullMethodName = "/hugo_admin.plugin.TTSGenerator/Generate"
	TTSGenerator_Delete_FullMethodName   = "/hugo_admin.plugin.TTSGenerator/Delete"
)

// TTSGeneratorClient is the client API for TTSGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TTSGeneratorClient interface {
	// Server-streaming: plugin emits Progress messages while synthesizing,
	// and a final Result carrying the public audio URL.
	Generate(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSResponse], error)
	// Delete a previously generated/hosted audio object.
	Delete(ctx context.Context, in *TTSDeleteRequest, opts ...grpc.CallOption) (*TTSDeleteResponse, error)
}

type tTSGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSGeneratorClient(cc grpc.ClientConnInterface) TTSGeneratorClient {
	return &tTSGeneratorClient{cc}
}

func (c *tTSGeneratorClient) Generate(ctx context.Context, in *TTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSGenerator_ServiceDesc.Streams[0], TTSGenerator_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TTSRequest, TTSResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSGenerator_GenerateClient = grpc.ServerStreamingClient[TTSResponse]

func (c *tTSGeneratorClient) Delete(ctx context.Context, in *TTSDeleteRequest, opts ...grpc.CallOption) (*TTSDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TTSDeleteResponse)
	err := c.cc.Invoke(ctx, TTSGenerator_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TTSGeneratorServer is the server API for TTSGenerator service.
// All implementations must embed UnimplementedTTSGeneratorServer
// for forward compatibility.
type TTSGeneratorServer interface {
	// Server-streaming: plugin emits Progress messages while synthesizing,
	// and a final Result carrying the public audio URL.
	Generate(*TTSRequest, grpc.ServerStreamingServer[TTSResponse]) error
	// Delete a previously generated/hosted audio object.
	Delete(context.Context, *TTSDeleteRequest) (*TTSDeleteResponse, error)
	mustEmbedUnimplementedTTSGeneratorServer()
}

// UnimplementedTTSGeneratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSGeneratorServer struct{}

func (UnimplementedTTSGeneratorServer) Generate(*TTSRequest, grpc.ServerStreamingServer[TTSResponse]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedTTSGeneratorServer) Delete(context.Context, *TTSDeleteRequest) (*TTSDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTTSGeneratorServer) mustEmbedUnimplementedTTSGeneratorServer() {}
func (UnimplementedTTSGeneratorServer) testEmbeddedByValue()                      {}

// UnsafeTTSGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSGeneratorServer will
// result in compilation errors.
type UnsafeTTSGeneratorServer interface {
	mustEmbedUnimplementedTTSGeneratorServer()
}

func RegisterTTSGeneratorServer(s grpc.ServiceRegistrar, srv TTSGeneratorServer) {
	// If the following call panics, it indicates UnimplementedTTSGeneratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTSGenerator_ServiceDesc, srv)
}

func _TTSGenerator_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TTSRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TTSGeneratorServer).Generate(m, &grpc.GenericServerStream[TTSRequest, TTSResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSGenerator_GenerateServer = grpc.ServerStreamingServer[TTSResponse]

func _TTSGenerator_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TTSDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSGeneratorServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSGenerator_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSGeneratorServer).Delete(ctx, req.(*TTSDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TTSGenerator_ServiceDesc is the grpc.ServiceDesc for TTSGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTSGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hugo_admin.plugin.TTSGenerator",
	HandlerType: (*TTSGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _TTSGenerator_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _TTSGenerator_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
